language: python

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

steps:
# (Other steps go here)
  - name: "Upload coverage to Codecov"
  uses: codecov/codecov-action@v1
  with:
      fail_ci_if_error: true
      token: 375795c4-8c70-4412-ab70-e9da8e897e6c