language: python
python:
  - "3.9"

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

steps:
  - name: "Upload coverage to Codecov"
  uses: codecov/codecov-action@v1
  with:
      fail_ci_if_error: true
