# Generated by Django 3.1.7 on 2021-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='', help_text='Tags vary according to content, e.g: Sports, Academics, Religion tags.', max_length=128),
        ),
    ]
