# Generated by Django 3.1.7 on 2021-03-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210301_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, help_text='Quote for the article. This is optional. Leave blank if you do not have an aritlce.', null=True),
        ),
    ]
