# Generated by Django 3.1.7 on 2021-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='This is the name of the sender.', max_length=256)),
                ('sender_mail', models.EmailField(max_length=254)),
                ('sender_subject', models.CharField(help_text='Subject of the messsage', max_length=1024)),
                ('sender_message', models.TextField()),
                ('sent_at', models.DateField(help_text='Date of Message')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='quote',
        ),
    ]
