# Generated by Django 3.1.7 on 2021-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210302_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principles', models.TextField()),
                ('location', models.TextField()),
                ('mission', models.TextField()),
                ('form_one_stream', models.TextField()),
                ('form_two_stream', models.TextField()),
                ('form_three_stream', models.TextField()),
                ('form_four_stream', models.TextField()),
                ('bom_message', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
