# Generated by Django 3.1.7 on 2021-03-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_webcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcontent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='webcontent',
            name='phone',
        ),
    ]
