# Generated by Django 3.1.7 on 2021-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210304_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcontent',
            name='bom_message',
            field=models.TextField(help_text='Message from BOM to parents and students.'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='form_four_stream',
            field=models.TextField(help_text='Form four slogan'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='form_one_stream',
            field=models.TextField(help_text='Form one Slogan'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='form_three_stream',
            field=models.TextField(help_text='Form three slogan'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='form_two_stream',
            field=models.TextField(help_text='Form two slogan'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='location',
            field=models.TextField(help_text='Location of the school'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='mission',
            field=models.TextField(help_text='Mission of the school'),
        ),
        migrations.AlterField(
            model_name='webcontent',
            name='principles',
            field=models.TextField(help_text="This is the 'Principles' section on the first page."),
        ),
    ]
