# Generated by Django 3.1.7 on 2021-03-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_stud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_level', models.CharField(choices=[('Admin', 'Admin'), ('Principal', 'Principa'), ('Deputy', 'Deputy'), ('Dean', 'Dean'), ('Academic Mistress', 'Academic Mistress'), ('Boarding Master', 'Boarding Master'), ('ICT', 'ICT'), ('Teacher', 'Teacher')], max_length=128)),
                ('account_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Stud',
        ),
    ]
