# Generated by Django 3.1.7 on 2021-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210321_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_status',
            field=models.BooleanField(default=False, help_text='The current status of the account. Default set to False until you (Admin) Approves.'),
        ),
    ]
