# Generated by Django 3.1.7 on 2021-03-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_status',
        ),
    ]
