# Generated by Django 3.1.7 on 2021-03-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210324_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
