# Generated by Django 3.1.7 on 2021-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210324_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_name',
        ),
    ]
