# Generated by Django 3.1.7 on 2021-03-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
